steps:
  - label: "Nvidia GPUs -- CUDA.jl"
    plugins:
      - JuliaCI/julia#v1:
          version: 1.8
      - JuliaCI/julia-test#v1: ~
    agents:
      queue: "juliagpu"
      cuda: "*"
    timeout_in_minutes: 30
