steps:
  - label: "Nvidia GPUs -- CUDA.jl"
    plugins:
      - JuliaCI/julia#v1:
          version: 1.8
    agents:
      queue: "juliagpu"
      cuda: "*"
    command: |
      julia --color=yes --project -e '
      using Pkg
      Pkg.instantiate()
      include("test/runtests.jl")'
    timeout_in_minutes: 30